# auth_service/docker-compose.yaml
services:
  auth_db:
    image: postgres:15-alpine
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  auth_redis:
    image: redis:alpine
    container_name: auth_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app-network

  auth_service:
    build: .
    image: sc-auth_service:1.0.0
    container_name: auth_service
    environment:
      - DB_HOST=auth_db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=auth_redis
      - REDIS_PORT=6379
          # App Configuration
      # - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
      - HTTP_PORT=8182
      - GRPC_SEKOLAH_HOST="sekolah_service:50052"
      - GRPC_SC_HOST="sc_service:50053"
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - JWT_PRIVATE_PATH=./keys/private.pem
      - JWT_PUBLIC_PATH=./keys/public.pem
    ports:
      - "8182:8182"
      - "50051:50051"
    networks:
      - app-network
    depends_on:
      - auth_db
      - auth_redis

networks:
  app-network:
    external: true
    name: app-network

volumes:
  auth_db_data: