# auth_service/docker-compose.yaml
services:
  auth_service:
    build: .
    container_name: auth_service_container
    environment:
      - DB_HOST=auth_db_container
      - DB_PORT=5432
      - DB_USER=${AUTHDB_USER}
      - DB_PASSWORD=${AUTHDB_PASSWORD}
      - DB_NAME=${AUTHDB_DB}
      - REDIS_HOST=auth_redis_container
      - REDIS_PORT=6379
    ports:
      - "8182:8182"
      - "50052:50052"
    networks:
      - app-network
    depends_on:
      - auth_db
      - auth_redis

  auth_db:
    image: postgres:15-alpine
    container_name: auth_db_container
    restart: always
    environment:
      POSTGRES_USER: ${AUTHDB_USER}
      POSTGRES_PASSWORD: ${AUTHDB_PASSWORD}
      POSTGRES_DB: ${AUTHDB_DB}
    ports:
      - "${AUTHDB_PORT}:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  auth_redis:
    image: redis:alpine
    container_name: auth_redis_container
    restart: always
    ports:
      - "${AUTHREDIS_PORT}:6379"
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network

volumes:
  auth_db_data: