version: "3.8"

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile.dev   # Dockerfile khusus dev
    container_name: auth_service_container
    depends_on:
      - auth_db
      - auth_redis
    volumes:
      - .:/app                     # mount source code lokal
      - go_mod_cache:/go/pkg/mod   # cache dependencies Go
    working_dir: /app
    command: air                   # jalankan dengan Air (hot reload)
    ports:
      - "${AUTHSERVICE_PORT}:8080"
    environment:
      DATABASE_URL: "postgres://${AUTHDB_USER}:${AUTHDB_PASSWORD}@auth_db:5432/${AUTHDB_DB}?sslmode=disable"
      REDIS_ADDR: "auth_redis:6379"

volumes:
  go_mod_cache:
