FROM golang:1.23-alpine AS builder

RUN apk add --no-cache git curl bash build-base
# Install Air versi yang masih support Go 1.23
RUN go install github.com/cosmtrek/air@v1.43.0

FROM golang:1.23-alpine
RUN apk add --no-cache git bash build-base

WORKDIR /app

# Set PATH
ENV PATH="$PATH:/go/bin"

# Copy binary air dari builder
COPY --from=builder /go/bin/air /usr/local/bin/air

COPY go.mod go.sum ./
RUN go mod download

CMD ["air"]
