services:
  scservice:
    # DEVELOPMENT MODE (uncomment below)
    build:
      context: .
      dockerfile: Dockerfile 
    volumes:
    - ./contracts:/app/contracts
    - ./build:/app/build
    # command: ["/app/sc-service"]  # Jalankan binary yang sudah dicompile
    container_name: ${GRPC_HOST}
    ports:
      - "8184:8184"
      - "50054:50054"
    env_file:
      - .env.prod
    environment: 
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: scdb_container
    restart: always
    # env_file:
    #   - .env.prod       # Untuk variabel non-sensitive
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: ${SCDB_DB}
    ports:
      - "5444:5432"
    volumes:
      - sc_db_cont_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    secrets:
      - db_user
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:                   # Hanya bekerja di Docker Swarm
      resources:
        limits:
          cpus: '1'
          memory: 2G
volumes:
  sc_db_cont_data:
secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt