events {}

http {
  server {
    listen 80;

    # Auth Service
    location /api/v1/as/ {
      proxy_pass         http://host.docker.internal:8182;
      proxy_set_header   Host $host;
      proxy_set_header   X-Real-IP $remote_addr;
      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_set_header   Cookie $http_cookie;
    }

    # Sekolah Service
    location /api/v1/ss/ {
      proxy_pass http://host.docker.internal:8183;
      proxy_set_header Host $host;
    }

    # Smart Contract Service
    location /api/v1/scs/ {
      proxy_pass http://host.docker.internal:8184;
      proxy_set_header Host $host;
    }
  }
}
